# Generated by Django 2.2.3 on 2020-10-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0002_auto_20200830_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='parent_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_occurence_set', to='activity_calendar.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_id',
            field=models.DateTimeField(blank=True, null=True, verbose_name='parent activity date/time'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='parent_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_slot_set', to='activity_calendar.Activity'),
        ),
    ]
