# Generated by Django 2.2.3 on 2020-10-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0003_auto_20201006_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'compound activities',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='compound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='activity_calendar.CompoundActivity'),
            preserve_default=False,
        ),
    ]
