# Generated by Django 2.2.3 on 2020-10-08 15:02

from django.db import migrations

def create_compound_per_activity_name(apps, schema_editor):
    # We can't import the Activity model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Activity = apps.get_model('activity_calendar', 'Activity')
    CompoundActivity = apps.get_model('activity_calendar', 'CompoundActivity')

    for activity in Activity.objects.all():
        compound, _ = CompoundActivity.objects.get_or_create(
            name=activity.title,
            defaults={'description': activity.description},
        )
        activity.compound = compound
        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0004_auto_20201008_1655'),
    ]

    operations = [
        # Each activity must have a CompoundActivity. As such, we merge create a single
        # new compoundActivity for all activities with the same name.
        migrations.RunPython(create_compound_per_activity_name),
    ]
