# Generated by Django 2.2.3 on 2020-10-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0005_auto_20201008_1702'),
    ]

    operations = [
        # Non-null handled in previous data migration
        migrations.AlterField(
            model_name='activity',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='activity_calendar.CompoundActivity'),
        ),
    ]
