# Generated by Django 2.2.5 on 2019-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=255)),
                ('members', models.ManyToManyField(blank=True, related_name='committee_members', to='membership_file.Member')),
            ],
        ),
    ]
