# Generated by Django 2.2.5 on 2019-09-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_committee_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='achievement',
        ),
    ]
